# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-30 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20171124_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
